### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by RohanAlexander** [eeeee-cmd/US_Election#6]
Marking is done so feel free to implement these if you'd like. Selfishly I'd like the tweaks made so I can use as an example, but they're just suggestions. 

- You don't need both a caption and a title. Just move everything into the caption, and then make every caption about twice as detailed as they currently are.
- Discussion subtitles need to be more informative. ATM they are very generic.
- Model results section - Would have been better to use  `modelsummary` table here for the model estimates. If too detailed then include the full one in an appendix and include a cut down one here.
- References: Fix "Times, The New York." - wrap the author in double braces in bibtex.

**Comment by sophiabrothers1** [comment]
I have updated the paper to reflect all of these suggestions! 
Note: I added the modelsummary table (table 1) to the model validation section (section 3.4) and deleted the RMSE table that was previously there since RMSE is depicted in the modelsummary table. The full modelsummary table (table 6) is attached in the appendix.

**Comment by RohanAlexander** [comment]
May I use as an example please? Oh also, feel free to manually set the date in the paper back to yesterday if you'd like.

**Comment by sophiabrothers1** [comment]
Yes of course! Just updated the date :)
